### ISSUE TITLE
Spec <-> Synapse divergence on default `invite` power levels

### ISSUE THREAD

**Issue by dkasak** [matrix-org/matrix-spec#1019]
The spec [says](https://spec.matrix.org/unstable/client-server-api/#mroompower_levels):

> The power level required to invite a user to the room, kick a user from the room, ban a user from the room, or redact an event sent by another user, is defined by `invite`, `kick`, `ban`, and `redact`, respectively. Each of these levels defaults to 50 if they are not specified in the `m.room.power_levels event`, or if the room contains no `m.room.power_levels` event.

But Synapse [defaults to 0](https://github.com/matrix-org/synapse/blob/f608e6c8cf48d8d5327c5ac04746f4f7f3992e31/synapse/event_auth.py#L351) for `invite` and has been doing that since forever:

    invite_level = get_named_level(auth_events, "invite", 0)

A few years ago, matrix.org had a problem with invite spam due to this and so the default `invite` power level [was raised in Synapse](https://github.com/matrix-org/synapse/pull/6834) during room creation to solve it, without realizing the divergence from the spec.

Changing it now would lead to many old events prior to that change getting rejected and is thus a no-go. At the same time, some implementations like Conduit do not always set a power level during room creation, leading to those rooms becoming split-brained between Synapse and Conduit.

What are we to do? I propose that we should relax the spec to require PL 0 instead of 50 for `invite` as this has been the de facto situation, bringing Synapse under compliance. Then, if the PL50 requirement for `invite` is still wanted, it can be brought back in a new room version. In the meantime, other implementations should mitigate the problem by always setting the `invite` power level during room creation.

# References

- [Previous spec issue](https://github.com/matrix-org/matrix-spec/issues/860)

**Comment by dkasak** [comment]
cc @richvdh for visibility.

**Comment by richvdh** [comment]
> A few years ago, matrix.org had a problem with invite spam due to this and so the default invite power level https://github.com/matrix-org/synapse/pull/6834 during room creation to solve it, without realizing the divergence from the spec.

this isn't really related here: that PR changed the content of the `m.room.power_levels` event generated by the `createRoom` API, but  made no change to the behaviour in the face of an `m.room.power_levels` event with no `invite` key, which is the problem here.

It's fairly clear that the PR which added this text to the spec (https://github.com/matrix-org/matrix-doc/pull/341) was just wrong, and this should be considered a spec bug, as annoying as it is.

And yes, we can consider changing the behaviour in future room versions separately.

In practice, this is very rarely encountered, since all `m.room.power_levels` events will have an `invite` key, unless the admin of a room is deliberately trying to provoke split-brained behaviour by omitting it.

**Comment by dkasak** [comment]
> this isn't really related here: that PR changed the content of the m.room.power_levels event generated by the createRoom API, but made no change to the behaviour in the face of an m.room.power_levels event with no invite key, which is the problem here.

It's related in the sense that Conduit doesn't have the same problem since it interpreted and implemented the spec literally, thus having a default of 50. The fact that Conduit does this differently is how this was now discovered in the first place. @timokoesters

> In practice, this is very rarely encountered, since all m.room.power_levels events will have an invite key, unless the admin of a room is deliberately trying to provoke split-brained behaviour by omitting it.

Well, since the spec doesn't actually say (I think) that you need to include `invite` in `m.room.power_levels` if you don't want trouble, it's not surprising that there are some implementations that started doing it.

**Comment by jplatte** [comment]
> In practice, this is very rarely encountered, since all `m.room.power_levels` events will have an `invite` key, unless the admin of a room is deliberately trying to provoke split-brained behaviour by omitting it.

This is actually very easy to encounter in practice:

* when using Conduit and the client doesn't specify a power level override, you get an empty power-levels content object
* when a client built on top of Ruma (usually through the Matrix Rust SDK) specifies an override

In both these cases, Ruma strips the default values because serializing them would be a waste of bandwidth.

**Comment by richvdh** [comment]
oh right. Generating power-levels events without explicit values for `invite` is probably not a great idea, for the same reasons as #6834.

**Comment by richvdh** [comment]
dup #860

**Comment by jplatte** [comment]
I don't really understand, what reasons?

**Comment by richvdh** [comment]
> I don't really understand, what reasons?

well, because the default for invite is zero (as discussed here and in #860), and https://github.com/matrix-org/synapse/pull/6834#issuecomment-1088565478.

**Comment by jplatte** [comment]
Oh, you're saying it's good to work around the spec bug the same Synapse and Element have basically been doing (albeit not explicitly as a spec bug workaround). We could certainly always serialize this field in Ruma, but honestly I like that these bugs in the spec and other software (AFAICT EleWeb is buggy in that it claims invite requires mod PL when omitted, still have to create an issue) are being discovered now rather than lingering on forever.
