### ISSUE TITLE
Canonical JSON: `0` vs `-0`

### ISSUE THREAD

**Issue by tonyg** [matrix-org/matrix-spec#1566]
**Link to problem area**: https://spec.matrix.org/v1.7/appendices/#canonical-json

**Issue**

In spec v1.7, in the "canonical JSON" appendix, it looks like both `0` and `-0` are allowed (both integers in range, leading minus permitted for all integers). `-0` should probably be explicitly disallowed.

**Comment by richvdh** [comment]
Agreed. I think this is just an omission from the words of the spec. A PR to fix it would be welcome.

As an aside: [RFC8785](https://www.rfc-editor.org/rfc/rfc8785.html#name-serialization-of-numbers) (a similar attempt at JSON Canonicalisation) doesn't seem to specify this either (though its job is harder because it tolerates floats),.

Related: https://github.com/matrix-org/matrix-spec/issues/1245

**Comment by tonyg** [comment]
Thanks. Here's a PR: #1573
