### ISSUE TITLE
Tapback Reactions

### ISSUE THREAD

**Issue by Feliks-WR** [matrix-org/matrix-spec#1960]
I would love to see tapback reactions, in which you can react to a reaction, just like or iMessage.

Reason:
Soooo many times, I find myself wanting to react to a reaction.
It would be a REALLY strong magnet towards Matrix, for non Matrix users.

It should be added to the protocol+ Element (X) first, then clients can add their own implementations.

Also, support for these should be added to Synapse as well, so that servers can incorporate the feature easily.

Perhaps, needing to make reactions end to end encrypted may become necessary.

**Comment by richvdh** [comment]
> It should be added to the protocol+ Element (X) first, then clients can add their own implementations.

That's not really how Matrix works: typically features are developed and standardised by a specific client implementation. Certainly features are never added to the Matrix specification without evidence of at least one implementation.

I'd suggest raising this in the issue tracker of individual clients, rather than here. (To be honest, it's not very clear what you're asking for: the term "tapback reaction" is meaningless to me, so I'd recommend being clearer in any new issues that you open.)

I'm going to close this here as I don't think it's actionable.
