### ISSUE TITLE
Per-device push rules

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#273]
*Note:* This previously was a question about what "device" push rules are. After some investigation (illustrated below) it was found that this is actually a feature we want to write, but is not an omission. 

----

Per-device push rules may be useful in some scenarios. A rough prototype exists in Riot for how these could work, where they are stored in account data and applied before the global push rules. This gives individual devices a chance to be notified differently.

More thought needs to be done about how to implement these specifically, however some reference material is available here:
* https://github.com/matrix-org/matrix-js-sdk/blob/4d310cd4618db4e98a8e6b5eb812480102ee4dee/src/pushprocessor.js#L207-L209
* https://github.com/matrix-org/matrix-js-sdk/blob/4d310cd4618db4e98a8e6b5eb812480102ee4dee/src/pushprocessor.js#L298-L308
* https://github.com/matrix-org/matrix-js-sdk/blob/4d310cd4618db4e98a8e6b5eb812480102ee4dee/src/pushprocessor.js#L106-L111

**Comment by richvdh** [comment]
per #673, we should remove these rather than document them.

**Comment by turt2live** [comment]
@richvdh wrong issue link? I can't really find which one you were looking for...

**Comment by turt2live** [comment]
(note that this issue is framed as a feature request, not a documentation omission)

**Comment by turt2live** [comment]
right, this issue is indeed not helpful then - reclosing.

**Comment by ownaginatious** [comment]
@turt2live curious, what was the conclusion here exactly?

I'm looking to filter out specific notifications for my iPhone. For context, I have an iMessage bridge setup for my non-Apple devices (`mautrix-imessage`) which works great. On my iPhone I'd prefer to use the official Messages client. The issue is, I have a Matrix client also installed on my iPhone (Element) and cannot silence the notifications from by iMessage bridge without also silencing them on all my other devices.

This should in theory be possible according to the Matrix spec with this:

```
PUT /_matrix/client/v3/pushrules/<scope:my-iphone-device-id>/sender/<rule_id:made-up-rule-id>

{
  "actions": [
    "dont_notify"
  ],
  "conditions": [{
    {"kind": "event_match", "key": "sender", "pattern": "@imessage_*"}
  }]
}
```

Looks like the actual `synapse` implementation is locked to only the `global` scope and has been for years: https://github.com/matrix-org/synapse/blob/6edefef60289cc54e17fd6af838eb66c4973f5f5/synapse/rest/client/push_rule.py#L191

The impression I get from this and the trail of issues connected to this topic is that everyone wants to move away from server-side device notification filtering for technical reasons.

In light of that, is there some other preferred way for achieving what I want server-side that is documented elsewhere, or should I take this issue over to the Element project to start a conversation about client-side notification filtering instead?

**Comment by clokep** [comment]
> per #673, we should remove these rather than document them.

I believe this should be #637.
