### ISSUE TITLE
The 'redacts' PDU field is not signed.

### ISSUE THREAD

**Issue by jevolk** [matrix-org/matrix-spec#277]
Server-Server [Section 17](https://matrix.org/docs/spec/server_server/unstable.html#signing-events) does not list `redacts` as an essential key.

As a non-essential key it is not included in JSON-signing and verification. An unsigned key is subject to arbitrary modification. An attacker can then redirect the target of a redaction event to any other event with the same authority as the sender.

**Comment by richvdh** [comment]
I don't think room v11 has any bearing on this, but yes I think it can be closed. As far as I can tell it has always been a non-issue.

**Comment by richvdh** [comment]
> I don't think room v11 has any bearing on this

Hrm. Room v11 does have bearing on this, but not for the reason given. The reason it has bearing on this is that, as of room v11, the `redacts` property is itself preserved under redaction, and therefore is included in the reference hash, which means it is part of the `event_id` and covered by the signature. (ie, MSC2176, rather than MSC2174).
