### ISSUE TITLE
Specify JWT login flow

### ISSUE THREAD

**Issue by oliverjanik** [matrix-org/matrix-spec#370]
There's a JWT in the config section for Matrix Synapse there's implementation for login type `m.login.jwt`

Can this be specified please?

**Comment by richvdh** [comment]
Synapse no longer supports `m.login.jwt` (https://github.com/matrix-org/synapse/issues/12597). It does have support for `org.matrix.login.jwt` (if you configure it appropriately) but that's best considered an implementation-specific extension rather than something that is appropriate for the general Matrix spec.
