### ISSUE TITLE
Power level values can be ints or strings 

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/matrix-spec#853]
A long time ago there was a bug in Synapse where the values for the power level were strings rather than ints. This was fixed, but in order to not break rooms Synapse continued to accept power level values that were either ints or strings.

This behaviour should be documented.

This behaviour is also implemented in gomatrixserverlib/Dendrite and Ruma/Conduit.

Ideally we should be able to only document this for v1 rooms, but I haven't checked if this was fixed before or after v2 rooms were introduced (but I assume so).

**Comment by turt2live** [comment]
for clarity, and because I never wrote it down, the plan is to address the last point at the same time as adding MSC3667 to the spec. It's mostly a matter of effort, and given we'll be in the area when writing the MSC up it makes sense to go back and fix the other room versions. 

If for some reason that ends up taking forever then we can obviously go through and write the words into the spec appropriately. I would encourage us to make an effort to get MSC3667 into an assigned room version, though.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-spec-proposals/pull/3667
