### ISSUE TITLE
Media in the content repo is not authed

### ISSUE THREAD

**Issue by kethinov** [matrix-org/matrix-spec#870]
Example, this was shared in a private 3 person chat, but anyone can view it: https://matrix.org/_matrix/media/v1/download/matrix.org/bSRWdHBFqtVzowZDhwRGbzDq

Most people I've recruited into Matrix are Google Hangouts refugees looking for an open platform. On Hangouts, you cannot view the web URL of an image in this way unless you're authenticated with the server and the user has shared it with you in a chat.

Would it be possible to support moving past security through obscurity at some point? Or, failing that, at least expire the images after a week or so?

This is concerning because it would be rather trivial for someone to write a simple app querying random alphanumeric strings to harvest images people have shared in private conversations.

**Comment by n0toose** [comment]
The assertions in this thread seem to assume that, and, please correct me if I am wrong:
- assumes a lot about the computational resources available to a party interested in obtaining files/"every computer belonging to a single person is equal".
- does not account for the fact that a range of (26*26)^24 gets increasingly more "insecure" the bigger a homeserver gets in regards to how many files are uploaded to it and how many files are generally available to it.
- does not account for the theoretical chance that such passwords will be much easier to crack in the future.
- assumes that non-end-to-end encrypted files should be readable to anyone other than the participants in the conversation, the recipients of the link to a file, and the server operators, *which is the expectation that Matrix itself sets towards the user*.

This "too negligible for most people to actually communicate it properly" approach is personally making me feel uneasy, even if it were possibly more likely for me to get struck by lighting, considering that there are opportunities [(in the future)](https://github.com/matrix-org/matrix-spec-proposals/pull/2461#discussion_r398982090) to actually bring the chance of anyone ever receiving anything down to an absolute zero.

**Comment by FlyveHest** [comment]
A comment on this, as far as I can see, this will break media being shared across bridges, unless these bridges relay binary data directly.

But in turn, this will defeat the purpose of protecting the media since it will be directy available on another platform, maybe without the original poster being aware of this.

**Comment by Iruwen** [comment]
Correct me if I'm wrong, but: this makes Matrix a great filesharing host. Just create an anonymous account and an unencrypted non-public room and upload whatever you want in chunks as big as the server allows, then let the world know about the URLs to be consumed by tools like JDownloader. With some more effort on the client side, having public access to encrypted chunks is even more perfidious. And the server operator is probably liable for any illegal content (hello DCMA takedown or worse).

**Comment by axelsimon** [comment]
@Iruwen In most (many?) legal regimes, you are only liable for things you know to be hosting, and become liable once you've been informed of the case (and often, the material must also be "manifestly illegal" or similar). Simply having something "bad" on your server doesn't automatically make you liable.

A lot of large services (such as Youtube) will automatically take something down as soon as they are notified that it could be problematic, because that's when their legal liability starts. But most of the time they don't care to check whether it is actually problematic, especially for copyright matters & fair use/dealing (hence DMCA takedown requests being weaponised).

**Comment by rltas** [comment]
Until this is resolved, I added a Lua script for the nginx reverse proxy which only allows media access for ip addresses that successfully accessed the /capabilities or /sync endpoints, which seem to be two authenticated ones that are reliably accessed first.

**Comment by immanuelfodor** [comment]
Could you please share the config, how can one achieve this? (It'd be great for me if it would be a full example, I mean with the Docker commands as well if possible, AFAIK nginx doesn't contain the Lua engine anymore, so I need to do something to have Lua besides nginx)

**Comment by rltas** [comment]
I can do that later, yeah. In my case it's integrated with https://github.com/spantaleev/matrix-docker-ansible-deploy and thus involves Traefik as well, but it should be easy to adapt.

**Comment by richvdh** [comment]
> Until this is resolved, I added a Lua script in my nginx reverse proxy which only allows media access for ip addresses that successfully accessed the /capabilities or /sync endpoints, which seem to be two authenticated ones that are reliably accessed first.

Be aware that this will break federation: it will mean that users on other servers will be unable to view media uploaded on your server.

**Comment by rltas** [comment]
Yeah I'm not federating, thanks for pointing that out. I guess if you're looking for some extra privacy without aiming for the obvious solution that is encryption, you'll have a specific reason for that tradeoff.

**Comment by n0toose** [comment]
@turt2live thanks!

**Comment by kethinov** [comment]
@turt2live the original link in my original post can still be viewed without authentication. Has this change gone live yet on the matrix.org homeserver? 

And will it apply to all previous media, or only to new media shared after the change goes live?

**Comment by turt2live** [comment]
The matrix.org homeserver's rollout is being worked out following the spec change - there should be more detail in a few weeks (watch the matrix.org blog for updates). 

The spec change does not add authentication to existing endpoints, but rather introduces new ones. Servers are being advised to *freeze* the unauthenticated endpoints, like the one linked above, rather than add authentication retroactively. Media from before the freeze will remain accessible on the old endpoints while new media will only be accessible on the new endpoints. This is what matrix.org plans to do as well.
