### ISSUE TITLE
Receipt example rendered poorly

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix-spec#948]
**Link to problem area**: https://spec.matrix.org/latest/client-server-api/#client-behaviour-4

**Issue**

The second half of the example is meant to be indented like the first half, this renders OK when just looking at [the markdown file](https://github.com/matrix-org/matrix-doc/blob/72ff5b92cbef143f976291789294ff98bc142711/content/client-server-api/modules/receipts.md#client-behaviour), but seems borked when view on spec.matrix.org.

The sentence at the bottom is also rendered oddly:

# spec.matrix.org screenshot

![image](https://user-images.githubusercontent.com/517124/145239373-d91bf62f-93be-47c7-9459-d0c56369e986.png)

# GitHub rendered:

![image](https://user-images.githubusercontent.com/517124/145239512-b9273ebd-1b77-4177-9887-e57175562104.png)

**Comment by uhoreg** [comment]
The original issue seems to be fixed in `/unstable`:

![image](https://user-images.githubusercontent.com/1012976/191285131-fab6598d-3b71-40cc-b2cc-8b9a9c886167.png)

However, the issue reported in https://github.com/matrix-org/matrix-spec/issues/948#issuecomment-1056003738 is still present.  @clokep can we close this issue, and create a new issue for the other one?

**Comment by clokep** [comment]
> The original issue seems to be fixed in `/unstable`:

Maybe fixed by #948? I couldn't really bisect easily.

> However, the issue reported in [#948 (comment)](https://github.com/matrix-org/matrix-spec/issues/948#issuecomment-1056003738) is still present. @clokep can we close this issue, and create a new issue for the other one?

Will do.

**Comment by clokep** [comment]
> > However, the issue reported in [#948 (comment)](https://github.com/matrix-org/matrix-spec/issues/948#issuecomment-1056003738) is still present. @clokep can we close this issue, and create a new issue for the other one?
> 
> Will do.

Actually, as far as I can tell this seems OK?

![image](https://user-images.githubusercontent.com/517124/191297820-32de9f02-125b-4396-88f2-0e4b32bb1b1c.png)

But there are no body parameters so this seems correct.

It looks like v1.1 didn't render well though:

![image](https://user-images.githubusercontent.com/517124/191298064-ee361889-7a38-4f89-8044-60de86dcee48.png)

**Comment by uhoreg** [comment]
Ah, OK.  I thought you were referring to the issue where the [yaml specifies that it can have body parameters](https://github.com/matrix-org/matrix-spec/blob/main/data/api/client-server/receipts.yaml#L69-L78), but because it's more-or-less free-form (it doesn't specify what parameters it can have), it doesn't render anything.  But that seems to be the same issue as https://github.com/matrix-org/matrix-spec/issues/740 so probably not necessary to create another issue.
